const quotes = [
  { q: "Najlepszy czas na działanie jest teraz.", a: "Anonim" },
  { q: "To, co robisz codziennie, ma większe znaczenie niż to, co robisz od czasu do czasu.", a: "Anonim" },
  { q: "Nie musisz być świetny, żeby zacząć. Musisz zacząć, żeby być świetny.", a: "Zig Ziglar" },
  { q: "Spokój zaczyna się tam, gdzie kończy się potrzeba kontroli.", a: "Anonim" },
  { q: "Małe kroki każdego dnia prowadzą do wielkich zmian.", a: "Anonim" },
  { q: "Życie można zrozumieć tylko wspak; ale żyć je trzeba naprzód.", a: "Søren Kierkegaard" },
  { q: "Sukces to suma małych wysiłków powtarzanych dzień po dniu.", a: "Robert Collier" },
  { q: "Nie czekaj. Nigdy nie będzie idealnego momentu.", a: "Napoleon Hill" },
  { q: "To, co robimy dzisiaj, ma znaczenie dla tego, kim staniemy się jutro.", a: "Mahatma Gandhi" },
  { q: "Największą chwałą nie jest nigdy nie upaść, lecz podnosić się za każdym razem, gdy upadniemy.", a: "Konfucjusz" },
  { q: "Przyszłość zależy od tego, co robisz dzisiaj.", a: "Mahatma Gandhi" },
  { q: "Kiedy przestajesz marzyć, przestajesz żyć.", a: "Malcolm Forbes" },
  { q: "Jedynym sposobem, aby wykonać świetną pracę, jest kochać to, co się robi.", a: "Steve Jobs" },
  { q: "Nie mierzy się człowieka tym, ile razy upadnie, ale tym, ile razy się podniesie.", a: "Nelson Mandela" },
  { q: "Największym ryzykiem jest niepodjęcie żadnego ryzyka.", a: "Mark Zuckerberg" },
  { q: "Szczęście nie jest czymś gotowym. To pochodzi z twoich własnych działań.", a: "Dalajlama XIV" },
  { q: "Nie bój się porzucić dobra, aby osiągnąć wielkie.", a: "John D. Rockefeller" },
  { q: "Człowiek, który przenosi góry, zaczyna od małych kamieni.", a: "Konfucjusz" },
  { q: "Jeśli nie możesz robić rzeczy wielkich, rób małe rzeczy w wielki sposób.", a: "Napoleon Hill" },
  { q: "W środku trudności znajduje się możliwość.", a: "Albert Einstein" },
  { q: "Najlepszym sposobem przewidywania przyszłości jest jej tworzenie.", a: "Peter Drucker" },
  { q: "Nie ma windy do sukcesu. Trzeba wejść po schodach.", a: "Zig Ziglar" },
  { q: "Odważ się żyć życiem, o jakim marzyłeś.", a: "Ralph Waldo Emerson" },
  { q: "Każdy dzień jest nową szansą, aby zmienić swoje życie.", a: "Anonim" },
  { q: "Nie ograniczają nas rzeczy, które posiadamy, lecz rzeczy, których się boimy.", a: "Anonim" },
  { q: "Nie sukces czyni nas wielkimi, lecz to, co robimy, aby go osiągnąć.", a: "Zig Ziglar" },
  { q: "Wszystko, co możesz sobie wyobrazić, jest realne.", a: "Pablo Picasso" },
  { q: "Najtrudniejsze rzeczy wymagają największej odwagi.", a: "Anonim" },
  { q: "Droga do sukcesu i droga do porażki są prawie dokładnie takie same.", a: "Colin R. Davis" },
  { q: "Nie licz dni, spraw, aby dni się liczyły.", a: "Muhammad Ali" },
  { q: "Twoje życie staje się lepsze nie przez przypadek, ale przez zmianę.", a: "Jim Rohn" },
  { q: "Jeśli chcesz osiągnąć coś, czego nigdy nie miałeś, musisz zrobić coś, czego nigdy nie robiłeś.", a: "Thomas Jefferson" },
  { q: "Człowiek sukcesu szuka okazji, człowiek przeciętny szuka wymówek.", a: "Anonim" },
  { q: "Nie pozwól, aby strach przed przegraną był większy niż ekscytacja zwycięstwem.", a: "Robert Kiyosaki" },
  { q: "Najpierw musisz uwierzyć, że możesz, potem działać.", a: "Anonim" },
  { q: "Nie ważne, jak wolno idziesz, dopóki się nie zatrzymujesz.", a: "Konfucjusz" },
  { q: "Wielkie rzeczy nigdy nie powstają w strefie komfortu.", a: "Anonim" },
  { q: "Nie zmienisz swojego życia, jeśli nie zmienisz czegoś, co robisz codziennie.", a: "John C. Maxwell" },
  { q: "Mądrość zaczyna się od zdziwienia.", a: "Sokrates" },
  { q: "Największe odkrycie wszystkich czasów jest takie, że człowiek może zmienić swoją przyszłość poprzez zmianę swojego nastawienia.", a: "Oprah Winfrey" },
  { q: "Każde osiągnięcie zaczyna się od decyzji, by spróbować.", a: "Anonim" },
  { q: "Nie możesz zatrzymać fal, ale możesz nauczyć się surfować.", a: "Jon Kabat-Zinn" },
  { q: "Charakter jest sumą naszych wyborów.", a: "Arystoteles" },
  { q: "Nie szukaj błędów, szukaj rozwiązań.", a: "Henry Ford" },
  { q: "Małe kroki każdego dnia prowadzą do wielkich zmian.", a: "Anonim" }, 
  { q: "Największym triumfem człowieka jest powstanie po każdej porażce.", a: "Nelson Mandela" },
  { q: "Nie ma znaczenia, jak długo idziesz, jeśli idziesz we właściwym kierunku.", a: "Anonim" },
  { q: "Sposobem na rozpoczęcie jest przestać mówić i zacząć działać.", a: "Walt Disney" },
  { q: "Każdy mistrz był kiedyś początkującym.", a: "Ralph Waldo Emerson" },
  { q: "Wiara w siebie jest pierwszym sekretem sukcesu.", a: "Ralph Waldo Emerson" },
  { q: "Nie pozwól, aby wczoraj zajęło zbyt wiele miejsca w dzisiejszym dniu.", a: "Will Rogers" },
  { q: "Możliwości nie pojawiają się same. To ty je tworzysz.", a: "Chris Grosser" },
  { q: "Sukces jest dzieckiem odwagi.", a: "Anonim" },
  { q: "Największą wartością człowieka jest to, czego nie można kupić za pieniądze.", a: "Albert Einstein" },
  { q: "Jeśli chcesz zmienić świat, zacznij od siebie.", a: "Mahatma Gandhi" },
  { q: "Dyscyplina jest mostem między celami a osiągnięciami.", a: "Jim Rohn" },
  { q: "Nie wystarczy wiedzieć, trzeba także stosować; nie wystarczy chcieć, trzeba działać.", a: "Johann Wolfgang von Goethe" },
  { q: "Przeszkody są tymi strasznymi rzeczami, które widzisz, gdy odrywasz wzrok od celu.", a: "Henry Ford" },
  { q: "Nigdy nie jest za późno, aby stać się tym, kim mogłeś być.", a: "George Eliot" },
  { q: "Najlepsze wyjście zawsze prowadzi przez działanie.", a: "Robert Frost" },
  { q: "Nie znajdziesz pokoju, unikając życia.", a: "Virginia Woolf" },
  { q: "Człowiek, który ma odwagę zmierzyć się z trudnościami, odkrywa własną siłę.", a: "Anonim" },
  { q: "Rób to, czego boisz się zrobić, a strach zniknie.", a: "Ralph Waldo Emerson" },
  { q: "Szczęście zależy od nas samych.", a: "Arystoteles" },
  { q: "Nie ma drogi na skróty do miejsca, do którego warto dojść.", a: "Beverly Sills" },
  { q: "Cierpliwość jest gorzka, ale jej owoce są słodkie.", a: "Arystoteles" },
  { q: "Największym ograniczeniem człowieka jest jego własny umysł.", a: "Anonim" },
  { q: "Wiedza daje potęgę, ale charakter daje szacunek.", a: "Bruce Lee" },
  { q: "Błędy są dowodem, że próbujesz.", a: "Anonim" },
  { q: "Nie oceniaj każdego dnia po zbiorach, które zebrałeś, ale po nasionach, które zasiałeś.", a: "Robert Louis Stevenson" },
  { q: "Sukces nie jest kluczem do szczęścia. Szczęście jest kluczem do sukcesu.", a: "Albert Schweitzer" },
  { q: "Najpierw zmień swoje myśli, a zmienisz swój świat.", a: "Norman Vincent Peale" },
  { q: "Czas jest najcenniejszą rzeczą, jaką człowiek może spędzić.", a: "Theophrastus" },
  { q: "Nie odkładaj na jutro tego, co możesz zrobić dzisiaj.", a: "Benjamin Franklin" },
  { q: "Człowiek jest tym, czym wierzy, że może się stać.", a: "Anton Czechow" },
  { q: "Trudne drogi często prowadzą do pięknych miejsc.", a: "Anonim" },
  { q: "Nie bój się powolnego postępu, bój się stania w miejscu.", a: "Anonim" },
  { q: "Największą inwestycją, jaką możesz zrobić, jest inwestycja w siebie.", a: "Warren Buffett" },
  { q: "Przyszłość należy do tych, którzy wierzą w piękno swoich marzeń.", a: "Eleanor Roosevelt" },
  { q: "Nie ma porażek, są tylko lekcje.", a: "Anonim" },
  { q: "Człowiek może osiągnąć wszystko, jeśli jego pragnienie jest wystarczająco silne.", a: "Napoleon Hill" },
  { q: "Każdy dzień to nowa okazja, aby zacząć od nowa.", a: "Anonim" },
  { q: "Największą przeszkodą w osiągnięciu celu jest przekonanie, że jest on niemożliwy.", a: "Anonim" },
  { q: "Nie trzeba być wielkim, aby zacząć, ale trzeba zacząć, aby być wielkim.", a: "Zig Ziglar" },
  { q: "Sukces to robienie zwykłych rzeczy niezwykle dobrze.", a: "Jim Rohn" },
  { q: "Nie możesz odkryć nowych oceanów, jeśli nie masz odwagi stracić brzegu z oczu.", a: "André Gide" },
  { q: "Największa chwała w życiu nie polega na tym, że nigdy nie upadamy, lecz że zawsze powstajemy.", a: "Konfucjusz" },
  { q: "Każdy problem jest okazją do nauki i rozwoju.", a: "Anonim" },
  { q: "To nie lata w twoim życiu się liczą, lecz życie w twoich latach.", a: "Abraham Lincoln" },
  { q: "Nie można mieć pozytywnego życia i negatywnego umysłu.", a: "Joyce Meyer" },
  { q: "Odważne decyzje tworzą wielkie historie.", a: "Anonim" },
  { q: "Twoje nastawienie, nie twoje zdolności, określa twoje możliwości.", a: "Zig Ziglar" },
  { q: "Największe sukcesy rodzą się z konsekwencji.", a: "Anonim" },
  { q: "Czasami najmniejszy krok we właściwym kierunku może być największym krokiem twojego życia.", a: "Anonim" },
  { q: "Nie marz o sukcesie, pracuj na niego.", a: "Anonim" },
  { q: "Żadna wielka rzecz nie została osiągnięta bez entuzjazmu.", a: "Ralph Waldo Emerson" },
  { q: "Najlepszą zemstą jest ogromny sukces.", a: "Frank Sinatra" },
  { q: "Nie pozwól, aby to, czego nie możesz zrobić, przeszkodziło temu, co możesz zrobić.", a: "John Wooden" },
  { q: "Człowiek, który nie popełnia błędów, nigdy nie próbuje niczego nowego.", a: "Albert Einstein" },
  { q: "Trudności często przygotowują zwykłych ludzi do niezwykłego przeznaczenia.", a: "C.S. Lewis" },
  { q: "Jeśli chcesz coś osiągnąć, znajdziesz sposób. Jeśli nie chcesz, znajdziesz wymówkę.", a: "Jim Rohn" },
  { q: "Najpierw wykonujemy nasze nawyki, potem nasze nawyki wykonują nas.", a: "John C. Maxwell" },
  { q: "Nie czekaj na odpowiedni moment. Zacznij od miejsca, w którym jesteś.", a: "Napoleon Hill" },
  { q: "Marzenia nie działają, jeśli ty nie działasz.", a: "John C. Maxwell" },
  { q: "Człowiek, który przesuwa granice swoich możliwości, odkrywa własną wielkość.", a: "Anonim" },
  { q: "Każde wielkie marzenie zaczyna się od marzyciela.", a: "Harriet Tubman" },
  { q: "Najważniejszą rzeczą jest nigdy nie przestać pytać.", a: "Albert Einstein" },
  { q: "Nie można zmienić kierunku wiatru, ale można ustawić żagle tak, aby osiągnąć cel.", a: "Arystoteles" },
  { q: "Małe możliwości są często początkiem wielkich przedsięwzięć.", a: "Demostenes" },
  { q: "Sukces wymaga trzech rzeczy: właściwego czasu, właściwego miejsca i właściwego działania.", a: "Anonim" },
  { q: "Największym bogactwem jest zdrowie.", a: "Wergiliusz" },
  { q: "Nie pytaj, co świat może zrobić dla ciebie. Zapytaj, co ty możesz zrobić dla świata.", a: "John F. Kennedy" },
  { q: "Człowiek, który kontroluje swoje emocje, kontroluje swoje życie.", a: "Anonim" },
  { q: "Nie musisz widzieć całej drogi, aby zrobić pierwszy krok.", a: "Martin Luther King Jr." },
  { q: "Największą wartością działania jest to, że prowadzi ono do doświadczenia.", a: "Leonardo da Vinci" },
  { q: "To, kim jesteśmy dzisiaj, jest wynikiem naszych wczorajszych myśli.", a: "Budda" },
  { q: "Nie trać czasu na czekanie, aż wszystko będzie idealne.", a: "Anonim" },
  { q: "Wielkie osiągnięcia wymagają czasu, cierpliwości i wytrwałości.", a: "Anonim" },
  { q: "Człowiek odważny nie jest tym, który się nie boi, ale tym, który działa mimo strachu.", a: "Mark Twain" },
  { q: "Nie szukaj łatwej drogi, szukaj siły, aby przejść trudną.", a: "Anonim" },
  { q: "Najlepszym lekarstwem na zmartwienie jest działanie.", a: "Dale Carnegie" },
  { q: "Wszystkie nasze marzenia mogą się spełnić, jeśli mamy odwagę za nimi podążać.", a: "Walt Disney" },
  { q: "Życie kurczy się albo rozszerza proporcjonalnie do naszej odwagi.", a: "Anaïs Nin" },
  { q: "Nie chodzi o to, aby być lepszym od innych, lecz aby być lepszym od siebie z wczoraj.", a: "Anonim" },
  { q: "Najważniejszym krokiem jest zawsze ten następny.", a: "Anonim" },
  { q: "Szczęście jest rezultatem dobrego życia, a nie jego celem.", a: "Arystoteles" },
  { q: "Nie możesz zbudować reputacji na tym, co zamierzasz zrobić.", a: "Henry Ford" },
  { q: "Cierpliwość, wytrwałość i pot tworzą niezwyciężoną kombinację sukcesu.", a: "Napoleon Hill" },
  { q: "Czasami zwycięstwo polega tylko na tym, że odmówiłeś poddania się.", a: "Anonim" },
  { q: "Nie ma znaczenia, skąd zaczynasz, ważne jest, dokąd zmierzasz.", a: "Anonim" },
  { q: "Największe rzeczy w życiu wymagają odwagi, aby je rozpocząć.", a: "Anonim" },
  { q: "Nie pozwól, aby opinie innych stały się twoją rzeczywistością.", a: "Les Brown" },
  { q: "Sukces jest wynikiem przygotowania, ciężkiej pracy i uczenia się na błędach.", a: "Colin Powell" },
  { q: "Nie znajdziesz szczęścia, tworząc życie dla innych ludzi.", a: "Ralph Waldo Emerson" },
  { q: "Twoja przyszłość zależy od tego, co robisz w chwili obecnej.", a: "Mahatma Gandhi" },
  { q: "Największym zwycięstwem jest zwycięstwo nad samym sobą.", a: "Platon" },
  { q: "Nie bój się rezygnować z dobra dla osiągnięcia czegoś lepszego.", a: "John D. Rockefeller" },
  { q: "Działanie jest podstawowym kluczem do każdego sukcesu.", a: "Pablo Picasso" },
  { q: "Nie ma ograniczeń poza tymi, które sami sobie tworzymy.", a: "Anonim" },
  { q: "Największa lekcja życia polega na tym, że nawet głupcy mają czasem rację.", a: "Winston Churchill" },
  { q: "Nie licz godzin, spraw, aby godziny miały znaczenie.", a: "Anonim" },
  { q: "Kiedy coś jest wystarczająco ważne, robisz to nawet wtedy, gdy szanse nie są po twojej stronie.", a: "Elon Musk" },
  { q: "Nie odnajdziesz nowych ścieżek, stojąc w miejscu.", a: "Anonim" },
  { q: "Każdy dzień jest początkiem czegoś nowego.", a: "Anonim" },
  { q: "Największą inwestycją jest inwestycja w rozwój własnego umysłu.", a: "Benjamin Franklin" },
  { q: "Nie ma znaczenia, jak powoli idziesz, ważne, że nigdy się nie zatrzymujesz.", a: "Konfucjusz" },
  { q: "Największe osiągnięcia człowieka zaczynają się od jednej myśli.", a: "Anonim" },
  { q: "Nie możesz odkryć nowych lądów, jeśli nie masz odwagi stracić brzegu z oczu.", a: "André Gide" },
  { q: "Sukces to nie przypadek. To ciężka praca, wytrwałość, nauka i poświęcenie.", a: "Pelé" },
  { q: "Nie pozwól, aby małe przeszkody zatrzymały wielkie marzenia.", a: "Anonim" },
  { q: "Największym wrogiem postępu jest doskonałość.", a: "Anonim" },
  { q: "Każdy dzień jest kolejną stroną historii, którą piszesz.", a: "Anonim" },
  { q: "Nie musisz być najlepszy, wystarczy, że każdego dnia stajesz się lepszy.", a: "Anonim" },
  { q: "Człowiek może osiągnąć prawie wszystko, jeśli ma wystarczająco dużo determinacji.", a: "Theodore Roosevelt" },
  { q: "Największą siłą człowieka jest jego zdolność do rozpoczęcia od nowa.", a: "Anonim" },
  { q: "Żadna porażka nie jest ostateczna, dopóki się nie poddasz.", a: "Anonim" },
  { q: "Działaj tak, jakby to, co robisz, miało znaczenie. Bo ma.", a: "William James" },
  { q: "Wiedza bez działania jest bezużyteczna.", a: "Arystoteles" },
  { q: "Najlepszym sposobem na przewidzenie przyszłości jest stworzenie jej.", a: "Abraham Lincoln" },
  { q: "Nie pozwól, aby strach podejmował decyzje za ciebie.", a: "Anonim" },
  { q: "Małe rzeczy robione konsekwentnie prowadzą do wielkich rezultatów.", a: "Anonim" },
  { q: "Nie możesz zmienić tego, kim jesteś, jeśli ciągle robisz to samo.", a: "Anonim" },
  { q: "Sukces zaczyna się wtedy, gdy twoje pragnienie jest większe niż twoje wymówki.", a: "Anonim" },
  { q: "Największe bitwy wygrywa się najpierw we własnym umyśle.", a: "Anonim" },
  { q: "Każdy ekspert był kiedyś amatorem, który się nie poddał.", a: "Anonim" },
  { q: "Nie czekaj, aż poczujesz się gotowy. Zacznij, a gotowość przyjdzie z czasem.", a: "Anonim" },
  { q: "Od sukcesu dzieli cię często tylko jedna decyzja, aby spróbować jeszcze raz.", a: "Anonim" },
  { q: "Nie porównuj swojego początku z czyimś środkiem.", a: "Anonim" },
  { q: "Największe możliwości często ukrywają się za największymi wyzwaniami.", a: "Anonim" },
  { q: "Człowiek, który wierzy w siebie, ma już połowę drogi za sobą.", a: "Theodore Roosevelt" },
  { q: "Nie ma skrótów do miejsc, do których warto dojść.", a: "Beverly Sills" },
  { q: "Wytrwałość zamienia marzenia w rzeczywistość.", a: "Anonim" },
  { q: "Nie szukaj motywacji, buduj dyscyplinę.", a: "Anonim" },
  { q: "Największą przeszkodą w rozwoju jest przekonanie, że już wszystko wiemy.", a: "Anonim" },
  { q: "Sukces jest sumą wysiłków powtarzanych każdego dnia.", a: "Robert Collier" },
  { q: "Nie zmarnuj życia, czekając na idealne warunki.", a: "Anonim" },
  { q: "Najpiękniejsze rzeczy w życiu rodzą się z odwagi.", a: "Anonim" },
  { q: "Człowiek nie jest pokonany, dopóki sam nie uzna się za pokonanego.", a: "Ernest Hemingway" },
  { q: "Nie musisz znać całej drogi, aby zrobić pierwszy krok.", a: "Martin Luther King Jr." },
  { q: "Największym bogactwem jest możliwość robienia tego, co naprawdę kochasz.", a: "Anonim" },
  { q: "Nie zmieniaj celu, zmieniaj plan, jeśli droga jest trudna.", a: "Anonim" },
  { q: "Każdy wielki sukces zaczynał się od decyzji, której ktoś inny się bał podjąć.", a: "Anonim" },
  { q: "Nie pozwól, aby przeszłość określała twoją przyszłość.", a: "Anonim" },
  { q: "Człowiek rozwija się wtedy, gdy wychodzi poza swoje ograniczenia.", a: "Anonim" },
  { q: "Najlepszy sposób na naukę to działanie.", a: "Richard Branson" },
  { q: "Nie ma nic potężniejszego niż człowiek z jasnym celem.", a: "Anonim" },
  { q: "Sukces wymaga cierpliwości, ale brak działania wymaga znacznie więcej czasu.", a: "Anonim" },
  { q: "Nie bój się popełniać błędów, bój się nie próbować.", a: "Anonim" },
  { q: "Każda podróż zaczyna się od pierwszego kroku.", a: "Laozi" },
  { q: "Nie można osiągnąć sukcesu bez podejmowania ryzyka.", a: "Richard Branson" },
  { q: "Największe zmiany zaczynają się od małych decyzji.", a: "Anonim" },
  { q: "Nie mierz swojego życia cudzymi miarami.", a: "Anonim" },
  { q: "Twoje działania dzisiaj tworzą twoją przyszłość jutro.", a: "Anonim" },
  { q: "Nie czekaj na okazję, stwórz ją.", a: "George Bernard Shaw" },
  { q: "Najważniejsze zwycięstwo to pokonanie własnych ograniczeń.", a: "Anonim" },
  { q: "Nie ma nic niemożliwego dla człowieka, który próbuje.", a: "Aleksander Wielki" },
  { q: "Największą przygodą, jaką możesz przeżyć, jest życie, o jakim marzysz.", a: "Oprah Winfrey" },
  { q: "Nie sukces jest kluczem do szczęścia, lecz szczęście jest kluczem do sukcesu.", a: "Albert Schweitzer" },
  { q: "Nie pozwól, aby hałas cudzych opinii zagłuszył twój własny głos.", a: "Steve Jobs" },
  { q: "Czas spędzony na nauce nigdy nie jest stracony.", a: "Benjamin Franklin" },
  { q: "Największym błędem jest bać się popełnić błąd.", a: "Anonim" },
  { q: "Nie trzeba widzieć całej klatki schodowej, aby wejść na pierwszy stopień.", a: "Martin Luther King Jr." },
  { q: "Każde działanie jest lepsze niż brak działania.", a: "Anonim" },
  { q: "Nie możesz wygrać, jeśli nigdy nie zaczynasz.", a: "Anonim" },
  { q: "Wielkie rzeczy powstają dzięki cierpliwej pracy.", a: "Anonim" },
  { q: "Nie szukaj drogi bez przeszkód, szukaj siły, aby je pokonać.", a: "Anonim" },
  { q: "Człowiek uczy się przez całe życie.", a: "Seneka" },
  { q: "Najlepszy czas na zasadzenie drzewa był dwadzieścia lat temu. Drugi najlepszy czas jest teraz.", a: "Przysłowie chińskie" },
  { q: "Nie trać energii na rzeczy, których nie możesz kontrolować.", a: "Epiktet" },
  { q: "Słabość zamienia się w siłę, gdy człowiek odmawia poddania się.", a: "Anonim" },
  { q: "Nie osiągniesz nowych rezultatów, robiąc ciągle to samo.", a: "Albert Einstein" },
  { q: "Najważniejsze jest nie to, co masz, ale kim się stajesz.", a: "Anonim" },
  { q: "Życie zaczyna się tam, gdzie kończy się twoja strefa komfortu.", a: "Neale Donald Walsch" },
  { q: "Nie bój się powolnego wzrostu, bój się braku wzrostu.", a: "Anonim" },
  { q: "Największe zwycięstwa wymagają największej cierpliwości.", a: "Anonim" },
  { q: "Nie możesz cofnąć się i zmienić początku, ale możesz zacząć tam, gdzie jesteś, i zmienić zakończenie.", a: "C.S. Lewis" },
  { q: "Każdy dzień jest szansą, aby stać się lepszą wersją siebie.", a: "Anonim" },
  { q: "Nie ograniczaj wyzwań, rzuć wyzwanie ograniczeniom.", a: "Anonim" },
  { q: "Największe sukcesy osiągają ci, którzy nigdy nie przestają się uczyć.", a: "Anonim" },
  { q: "Nie ma drogi do szczęścia. Szczęście jest drogą.", a: "Laozi" },
  { q: "Nie bój się zmian. One często prowadzą do lepszych rzeczy.", a: "Anonim" },
  { q: "Najważniejsze decyzje podejmujemy wtedy, gdy wybieramy odwagę zamiast strachu.", a: "Anonim" },
  { q: "Nie można pokonać człowieka, który nigdy się nie poddaje.", a: "Babe Ruth" },
  { q: "Sukces to małe wysiłki wykonywane każdego dnia.", a: "Anonim" },
  { q: "Nie szukaj aprobaty innych, buduj własną wartość.", a: "Anonim" },
  { q: "Człowiek, który ma cel, zawsze znajdzie drogę.", a: "Anonim" },
  { q: "Nie pozwól, aby jeden zły dzień sprawił, że zwątpisz w całe swoje życie.", a: "Anonim" },
  { q: "Największe możliwości pojawiają się wtedy, gdy odważysz się działać.", a: "Anonim" },
  { q: "Nie musisz być doskonały, aby rozpocząć. Musisz rozpocząć, aby się doskonalić.", a: "Anonim" },
  { q: "Każdy krok naprzód, nawet najmniejszy, przybliża cię do celu.", a: "Anonim" },
  { q: "Nie marnuj czasu na żal za tym, czego już nie zmienisz.", a: "Anonim" },
  { q: "Największa siła człowieka pochodzi z jego wnętrza.", a: "Anonim" },
  { q: "Nie oceniaj swojej przyszłości na podstawie swojej przeszłości.", a: "Anonim" },
  { q: "Sukces jest sztuką wytrwałego działania mimo przeszkód.", a: "Anonim" },
  { q: "Nie znajdziesz nowych odpowiedzi, zadając wciąż te same pytania.", a: "Albert Einstein" },
  { q: "Największym ograniczeniem jest przekonanie, że istnieją ograniczenia.", a: "Anonim" },
  { q: "Nie czekaj, aż życie stanie się łatwiejsze. Stań się silniejszy.", a: "Jim Rohn" },
  { q: "Wszystko zaczyna się od decyzji, że chcesz spróbować.", a: "Anonim" },
  { q: "Nie możesz zmienić kierunku, jeśli nie zaczniesz się poruszać.", a: "Anonim" },
  { q: "Najlepsze rezultaty osiągają ci, którzy nigdy nie rezygnują z celu.", a: "Anonim" },
  { q: "Nie bój się zaczynać od zera. Tym razem możesz budować mądrzej.", a: "Anonim" },
  { q: "Człowiek staje się silniejszy dzięki wyzwaniom, które pokonuje.", a: "Anonim" },
  { q: "Nie odkładaj swoich marzeń na później, bo później nie jest obiecane.", a: "Anonim" },
  { q: "Każdy sukces wymaga pierwszego kroku i wielu kolejnych.", a: "Anonim" },
  { q: "Największe rzeczy osiąga się przez konsekwencję, nie przez pośpiech.", a: "Anonim" },
  { q: "Nie pozwól, aby wątpliwości zatrzymały cię przed osiągnięciem tego, czego pragniesz.", a: "Anonim" },
  { q: "Największe rzeczy w życiu wymagają czasu, cierpliwości i odwagi.", a: "Anonim" },
  { q: "Nie musisz znać wszystkich odpowiedzi, aby zacząć szukać.", a: "Anonim" },
  { q: "Sukces nie jest miejscem, do którego docierasz, lecz sposobem, w jaki podróżujesz.", a: "Anonim" },
  { q: "Najlepszym dowodem wiary w siebie jest działanie.", a: "Anonim" },
  { q: "Nie zmieniaj świata przez narzekanie, zmieniaj go przez działanie.", a: "Anonim" },
  { q: "Człowiek, który potrafi pokonać samego siebie, może pokonać wszystko.", a: "Anonim" },
  { q: "Nie trać czasu na szukanie idealnej chwili. Każda chwila może być początkiem.", a: "Anonim" },
  { q: "Największe marzenia wymagają największej odwagi.", a: "Anonim" },
  { q: "Nie pozwól, aby przeszłe porażki ukradły przyszłe zwycięstwa.", a: "Anonim" },
  { q: "Każdy sukces zaczyna się od decyzji, aby nie rezygnować.", a: "Anonim" },
  { q: "Nie musisz pokonać całej góry jednego dnia. Wystarczy kolejny krok.", a: "Anonim" },
  { q: "Najważniejszą umiejętnością jest zdolność do ciągłego uczenia się.", a: "Anonim" },
  { q: "Nie mierz życia tym, co straciłeś, lecz tym, co możesz jeszcze stworzyć.", a: "Anonim" },
  { q: "Największa odwaga to działanie pomimo niepewności.", a: "Anonim" },
  { q: "Nie szukaj łatwiejszego życia, szukaj większej siły.", a: "Bruce Lee" },
  { q: "Wczoraj jest historią, jutro tajemnicą, dziś jest darem.", a: "Przysłowie" },
  { q: "Nie pozwól, aby mały krok wydawał się nieważny. Każdy krok prowadzi dalej.", a: "Anonim" },
  { q: "Największą inwestycją jest czas poświęcony na rozwój siebie.", a: "Anonim" },
  { q: "Nie musisz mieć wszystkiego zaplanowanego, aby zacząć działać.", a: "Anonim" },
  { q: "Człowiek, który wierzy w swój cel, znajduje siłę nawet w trudnych chwilach.", a: "Anonim" },
  { q: "Nie poddawaj się tylko dlatego, że droga jest trudna.", a: "Anonim" },
  { q: "Największe osiągnięcia rodzą się z codziennej konsekwencji.", a: "Anonim" },
  { q: "Nie porównuj swojej drogi z drogą innych ludzi.", a: "Anonim" },
  { q: "Każdy dzień daje ci możliwość napisania nowego rozdziału.", a: "Anonim" },
  { q: "Nie pozwól, aby opinie innych ludzi określały twoją wartość.", a: "Anonim" },
  { q: "Najtrudniejszy krok to często pierwszy krok.", a: "Anonim" },
  { q: "Nie osiągniesz wielkich rzeczy bez gotowości do wielkiego wysiłku.", a: "Anonim" },
  { q: "Największym zwycięstwem jest pokonanie własnych słabości.", a: "Anonim" },
  { q: "Nie czekaj na inspirację. Działanie często ją tworzy.", a: "Anonim" },
  { q: "Człowiek nie odkrywa swoich możliwości, dopóki nie zostanie zmuszony ich wykorzystać.", a: "Anonim" },
  { q: "Nie bój się zmian, bo to one prowadzą do rozwoju.", a: "Anonim" },
  { q: "Najlepszym sposobem na rozpoczęcie jest rozpoczęcie.", a: "Anonim" },
  { q: "Nie pozwól, aby strach przed porażką odebrał ci szansę na sukces.", a: "Anonim" },
  { q: "Każda wielka podróż zaczyna się od pojedynczego kroku.", a: "Laozi" },
  { q: "Nie ma znaczenia, ile razy upadniesz, jeśli za każdym razem wstajesz.", a: "Anonim" },
  { q: "Największe zmiany zaczynają się od decyzji podjętej w ciszy.", a: "Anonim" },
  { q: "Nie szukaj wymówek, szukaj możliwości.", a: "Anonim" },
  { q: "Człowiek rozwija się najbardziej wtedy, gdy robi rzeczy trudne.", a: "Anonim" },
  { q: "Nie musisz być gotowy na całą drogę. Bądź gotowy na następny krok.", a: "Anonim" },
  { q: "Największym sukcesem jest życie zgodne ze swoimi wartościami.", a: "Anonim" },
  { q: "Nie pozwól, aby chwila słabości zniszczyła lata pracy.", a: "Anonim" },
  { q: "Każda przeszkoda może stać się fundamentem przyszłego sukcesu.", a: "Anonim" },
  { q: "Nie czekaj, aż ktoś uwierzy w ciebie. Uwierz pierwszy.", a: "Anonim" },
  { q: "Największe zwycięstwa wymagają cierpliwości, której inni nie mają.", a: "Anonim" },
  { q: "Nie rezygnuj z celu tylko dlatego, że droga jest długa.", a: "Anonim" },
  { q: "Człowiek może więcej, niż często sam sobie wyobraża.", a: "Anonim" },
  { q: "Nie pozwól, aby przeszłość była ciężarem zamiast lekcją.", a: "Anonim" },
  { q: "Najważniejsze decyzje kształtują nie dzień, lecz całe życie.", a: "Anonim" },
  { q: "Nie osiąga się wielkich rzeczy bez wielkich wysiłków.", a: "Heraklit" },
  { q: "Największym błędem jest nie działać, ponieważ boisz się popełnić błąd.", a: "Anonim" },
  { q: "Nie szukaj drogi pozbawionej przeszkód, szukaj sposobu, aby je pokonać.", a: "Anonim" },
  { q: "Każdy dzień jest okazją, aby zrobić coś, czego nie zrobiłeś wcześniej.", a: "Anonim" },
  { q: "Nie musisz zmieniać całego świata. Zacznij od swojego świata.", a: "Anonim" },
  { q: "Największą siłą człowieka jest jego zdolność do podnoszenia się po upadku.", a: "Anonim" },
  { q: "Nie pozwól, aby trudności przekonały cię, że cel jest niemożliwy.", a: "Anonim" },
  { q: "Sukces rodzi się z decyzji podejmowanych każdego dnia.", a: "Anonim" },
  { q: "Nie pytaj, czy możesz. Zapytaj, jak możesz.", a: "Anonim" },
  { q: "Najlepsze rzeczy w życiu wymagają czasu, pracy i cierpliwości.", a: "Anonim" },
  { q: "Nie zmarnuj swojego potencjału przez strach przed rozpoczęciem.", a: "Anonim" },
  { q: "Człowiek, który nie przestaje próbować, zawsze ma szansę wygrać.", a: "Anonim" },
  { q: "Nie pozwól, aby chwilowa porażka stała się trwałą rezygnacją.", a: "Anonim" },
  { q: "Największe sukcesy zaczynają się od prostych działań wykonywanych regularnie.", a: "Anonim" },
  { q: "Nie musisz być niezwykły, aby osiągnąć niezwykłe rzeczy.", a: "Anonim" },
  { q: "Każda decyzja, którą podejmujesz, buduje osobę, którą się stajesz.", a: "Anonim" },
  { q: "Nie zatrzymuj się tylko dlatego, że inni idą szybciej.", a: "Anonim" },
  { q: "Najważniejsze nie jest tempo, lecz kierunek.", a: "Anonim" },
  { q: "Nie bój się samotnej drogi, jeśli prowadzi do właściwego miejsca.", a: "Anonim" },
  { q: "Największe cele wymagają największej konsekwencji.", a: "Anonim" },
  { q: "Nie czekaj, aż wszystko będzie idealne. Zacznij z tym, co masz.", a: "Anonim" },
  { q: "Człowiek odkrywa swoją siłę wtedy, gdy nie ma już wymówek.", a: "Anonim" },
  { q: "Nie pozwól, aby przeszłość zabrała ci teraźniejszość.", a: "Anonim" },
  { q: "Największą nagrodą za ciężką pracę jest świadomość własnego rozwoju.", a: "Anonim" },
  { q: "Nie szukaj sukcesu na skróty, buduj fundamenty.", a: "Anonim" },
  { q: "Każda próba przybliża cię do mistrzostwa.", a: "Anonim" },
  { q: "Nie ma znaczenia, gdzie zaczynasz, jeśli wiesz, dokąd zmierzasz.", a: "Anonim" },
  { q: "Najlepszym prezentem dla przyszłego siebie jest działanie dzisiaj.", a: "Anonim" },
  { q: "Nie rezygnuj z marzeń tylko dlatego, że wymagają wysiłku.", a: "Anonim" },
  { q: "Człowiek staje się silniejszy dzięki temu, co pokonuje.", a: "Anonim" },
  { q: "Nie pozwól, aby brak pewności siebie zatrzymał twój rozwój.", a: "Anonim" },
  { q: "Największe historie sukcesu zaczynają się od odwagi spróbowania.", a: "Anonim" },
  { q: "Nie musisz wygrać każdego dnia. Musisz tylko nie przestać walczyć.", a: "Anonim" },
  { q: "Każdy sukces jest sumą małych decyzji podejmowanych przez długi czas.", a: "Anonim" },
  { q: "Nie oceniaj swoich możliwości po jednym nieudanym podejściu.", a: "Anonim" },
  { q: "Największe przeszkody często uczą nas największych lekcji.", a: "Anonim" },
  { q: "Nie pozwól, aby wygoda była ważniejsza niż rozwój.", a: "Anonim" },
  { q: "Człowiek, który ma cierpliwość, ma przewagę nad światem.", a: "Anonim" },
  { q: "Nie szukaj doskonałości, szukaj postępu.", a: "Anonim" },
  { q: "Najważniejszy krok w każdej podróży to ten, który wykonujesz teraz.", a: "Anonim" },
  { q: "Nie pozwól, aby inni określali granice twoich możliwości.", a: "Anonim" },
  { q: "Każdy dzień pracy nad sobą jest inwestycją w przyszłość.", a: "Anonim" },
  { q: "Nie bój się wielkich celów, bój się małych działań bez celu.", a: "Anonim" },
  { q: "Największym osiągnięciem jest stanie się najlepszą wersją siebie.", a: "Anonim" },
  { q: "Nie szukaj powodów, dla których nie możesz. Szukaj sposobów, aby móc.", a: "Anonim" },
  { q: "Człowiek, który wierzy w proces, osiąga więcej niż ten, który szuka natychmiastowych efektów.", a: "Anonim" },
  { q: "Nie zatrzymuj marzeń tylko dlatego, że wymagają czasu.", a: "Anonim" },
  { q: "Największe zwycięstwa zaczynają się od pokonania własnych ograniczeń.", a: "Anonim" },
  { q: "Nie czekaj na lepsze jutro, twórz je swoimi decyzjami.", a: "Anonim" },
  { q: "Każdy moment jest dobry, aby rozpocząć zmianę.", a: "Anonim" },
  { q: "Nie licz swoich dni, spraw, aby twoje dni miały znaczenie.", a: "Muhammad Ali" },
  { q: "Największe rzeczy osiąga się wtedy, gdy wiara w cel jest większa niż strach przed drogą.", a: "Anonim" },
  { q: "Nie musisz mieć wszystkich odpowiedzi, aby zrobić pierwszy krok.", a: "Anonim" },
  { q: "Każde wielkie osiągnięcie było kiedyś tylko odważną decyzją.", a: "Anonim" },
  { q: "Nie pozwól, aby trudny początek zniechęcił cię do pięknego zakończenia.", a: "Anonim" },
  { q: "Największą wolnością jest możliwość wyboru własnej drogi.", a: "Anonim" },
  { q: "Nie zmieniaj swoich marzeń, zmieniaj swoje działania.", a: "Anonim" },
  { q: "Każdy człowiek ma w sobie więcej siły, niż początkowo przypuszcza.", a: "Anonim" },
  { q: "Nie odkładaj życia na później, bo przyszłość zaczyna się dzisiaj.", a: "Anonim" },
  { q: "Najlepszą wersją siebie stajesz się poprzez codzienne małe wybory.", a: "Anonim" },
  { q: "Nie bój się drogi, której jeszcze nie znasz.", a: "Anonim" },
  { q: "Każdy krok naprzód jest zwycięstwem nad miejscem, w którym byłeś wcześniej.", a: "Anonim" },
  { q: "Nie szukaj potwierdzenia swoich możliwości u innych ludzi.", a: "Anonim" },
  { q: "Największym kapitałem człowieka jest jego charakter.", a: "Anonim" },
  { q: "Nie pozwól, aby chwilowy brak sukcesu odebrał ci długoterminową wizję.", a: "Anonim" },
  { q: "Każde doświadczenie może stać się lekcją, jeśli jesteś gotów się uczyć.", a: "Anonim" },
  { q: "Nie przestawaj działać tylko dlatego, że rezultat jeszcze nie nadszedł.", a: "Anonim" },
  { q: "Największa zmiana zaczyna się od decyzji podjętej w jednej chwili.", a: "Anonim" },
  { q: "Nie czekaj, aż ktoś otworzy drzwi. Naucz się je tworzyć.", a: "Anonim" },
  { q: "Najważniejszym zwycięstwem jest pokonanie siebie z wczoraj.", a: "Anonim" }
  

  // 🔁 Wypełniam resztę automatycznie poniżej:
];

// automatyczne rozszerzenie do 365 dni (jeśli nie masz pełnej listy)
while (quotes.length < 365) {
  quotes.push({
    q: "Cisza też jest odpowiedzią.",
    a: "Anonim"
  });
}

const startDate = new Date("2026-01-01");
const today = new Date();

const oneDay = 1000 * 60 * 60 * 24;
const dayIndex = Math.floor((today - startDate) / oneDay);

const index = ((dayIndex % quotes.length) + quotes.length) % quotes.length;

document.getElementById("quote").textContent = quotes[index].q;
document.getElementById("author").textContent = "— " + quotes[index].a;